# Tipos de arrays


In [ ]:
#isso é um array unidimensional
frutas = ['Maçã', 'Banana', 'Laranja', 'Manga']
print(frutas[0])  # Saída: 'Maçã'


#Alterando o valor dos dados:
frutas[1] = 'Pera'
print(frutas)  # Saída: ['Maçã', 'Pera', 'Laranja', 'Manga']

#percorrendo os valores:
for fruta in frutas:
    print(fruta)

#realizando calculos
numeros = [5, 10, 15, 20]
soma = sum(numeros)
print(soma)  # Saída: 50


Maçã
['Maçã', 'Pera', 'Laranja', 'Manga']


In [ ]:
#isso é um array bidimensional
notas_alunos = [
    [8, 7, 9],  # Aluno 1
    [6, 8, 7],  # Aluno 2
    [9, 9, 10]  # Aluno 3
]
print(notas_alunos[2][2])  # Saída: 7 (nota do aluno 2 na 3ª disciplina)
#Cada linha representa um aluno, e cada número dentro de uma linha representa as notas nas disciplinas.

#Alterando os valores
notas_alunos[2][1] = 10  # Mudando a nota do aluno 3 na 2ª disciplina
print(notas_alunos)

#percorrendo os valores
for i in range(len(notas_alunos)):
    soma = 0
    for j in range(len(notas_alunos[i])):
        soma += notas_alunos[i][j]
    print(f"Soma das notas do aluno {i + 1}: {soma}")

#realizando calculos
aluno = notas_alunos[0]
soma_notas = sum(aluno)
media = soma_notas / len(aluno)
print(f"Média do Aluno 1: {media}")


10
[[8, 7, 9], [6, 8, 7], [9, 10, 10]]
Soma das notas do aluno 1: 24
Soma das notas do aluno 2: 21
Soma das notas do aluno 3: 29


In [ ]:
#isso é um array tridimensional
vendas = [
    [  # Cidade 1
        [150, 200, 250],  # Janeiro
        [180, 220, 300]   # Fevereiro
    ],
    [  # Cidade 2
        [130, 170, 190],  # Janeiro
        [140, 180, 210]   # Fevereiro
    ]
]
print(vendas[0][1][2])  # Saída: 190 (vendas da Cidade 2 em Janeiro, 3º valor)

# Agora imagine que você está guardando as vendas de uma loja em várias cidades durante os meses de um ano. Cada cidade tem suas próprias vendas registradas mensalmente:
# Aqui temos duas cidades, e em cada uma delas, há vendas mensais organizadas em três meses (janeiro, fevereiro e março). Cada cidade tem um "bloco" com seus dados.

vendas[0][1][0] = 250  # Alterando o valor de vendas de Fevereiro na Cidade 1
print(vendas)

#Percorrendo os valores
for i in range(len(vendas)):
    print(f"Cidade {i + 1}")
    for j in range(len(vendas[i])):
        print(f"  Mês {j + 1}: {vendas[i][j]}")

# realizando calculos
total_vendas_cidade1 = 0
for i in range(len(vendas[0])):
    for j in range(len(vendas[0][i])):
        total_vendas_cidade1 += vendas[0][i][j]
print(f"Total de vendas da Cidade 1: {total_vendas_cidade1}")


300
[[[150, 200, 250], [250, 220, 300]], [[130, 170, 190], [140, 180, 210]]]
Cidade 1
  Mês 1: [150, 200, 250]
  Mês 2: [250, 220, 300]
Cidade 2
  Mês 1: [130, 170, 190]
  Mês 2: [140, 180, 210]
Total de vendas da Cidade 1: 1370


# Falando sobre numpy

## biblioteca para tratamento de dados através de estruturas de dados `array`



In [ ]:
import numpy as np #import do numpy e referenciando ela como np

In [ ]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [ ]:
#criar o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float32)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

In [ ]:
# podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
# mais de uma dimensão
# cria um matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [ ]:
#criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios
#sempre será primeiro linhas e depois colunas
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-------")
# cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("-------")
#com valores igual a um
um = np.ones([5,7])
print(um)
print("-------")
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(6)
print(diagonal)


[[101910002252002               0]
 [   416611827815    137438953580]
 [   433791697011    459561500773]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("-------")
#valores aleatórios distr. normal contendo negativos
ale2= np.random.randn((5))
print(ale2)
print("-------")
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.0422805  0.35323114 0.39241982 0.229691   0.64103444]
-------
[-3.06921214  0.16474446 -0.51757622  1.30608445  1.62557704]
-------
[[9.58715097 6.31580549 9.89100945 7.10606314]
 [9.1682775  8.25885976 7.52589763 8.34701697]
 [0.25150773 2.38913404 5.71520811 5.02492413]]


In [ ]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [ ]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz k
#primeiro eu especifico a linha e depois a coluna
print(k[0][1])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [ ]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [ ]:
#funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

In [ ]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [ ]:
#extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [ ]:
#adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print("-------")
res2 = n*o
print(res2)
print("-------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [ ]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
# rearranja um conjunto de 15 elementos
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1) # se x for maior que 0 então ele vai imprimir 1, caso contraário, ele imprimi -1
print(z)

